import React from 'react';
import { MoodCocktail } from '../types';

interface ShareCardProps {
  cocktail: MoodCocktail;
  onClose: () => void;
  title: string;
}

const ShareCard: React.FC<ShareCardProps> = ({ cocktail, onClose, title }) => {
  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/95 backdrop-blur-sm p-4 animate-fadeIn">
       <button 
        onClick={onClose} 
        className="absolute top-6 right-6 text-slate-400 hover:text-white z-50"
      >
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-8 h-8">
          <path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12" />
        </svg>
      </button>

      {/* The Card - Designed to be screenshotted */}
      <div className="relative w-full max-w-[340px] aspect-[9/16] bg-slate-900 rounded-[2rem] overflow-hidden shadow-2xl border border-white/10 flex flex-col items-center text-center p-8 select-none">
        
        {/* Abstract Background Gradient */}
        <div 
           className="absolute inset-0 opacity-40 blur-3xl"
           style={{ 
             background: `radial-gradient(circle at 50% 30%, ${cocktail.baseColor}, ${cocktail.secondaryColor}, transparent)` 
           }}
        />

        {/* Date */}
        <div className="relative z-10 text-[10px] uppercase tracking-widest text-slate-400 mt-2">
            {new Date(cocktail.createdAt).toLocaleDateString()}
        </div>

        {/* Visual Focus */}
        <div className="relative z-10 flex-grow flex items-center justify-center my-4">
             <div className="w-40 h-40 rounded-full bg-gradient-to-tr from-white/10 to-white/5 backdrop-blur-md border border-white/20 flex items-center justify-center shadow-[0_0_30px_rgba(255,255,255,0.05)]">
                 <div 
                   className="w-32 h-32 rounded-full opacity-80 blur-xl"
                   style={{ background: `linear-gradient(to bottom, ${cocktail.baseColor}, ${cocktail.secondaryColor})` }}
                 />
             </div>
        </div>

        {/* Typography */}
        <div className="relative z-10 mb-8">
            <h2 className="font-serif text-3xl text-white mb-3 leading-tight">{cocktail.name}</h2>
            <div className="w-12 h-1 bg-white/20 mx-auto mb-4 rounded-full" />
            <p className="font-sans text-xs text-slate-300 leading-relaxed font-light italic px-2 opacity-90">
                "{cocktail.description}"
            </p>
        </div>

        {/* Footer / QR Sim */}
        <div className="relative z-10 w-full flex justify-between items-end border-t border-white/10 pt-4">
            <div className="text-left">
                <div className="text-sm font-serif font-bold text-white">Mood Mixology</div>
                <div className="text-[9px] text-slate-500 uppercase tracking-wider">Generated by AI</div>
            </div>
            
            {/* Fake QR Code */}
            <div className="bg-white p-1 rounded-sm">
                <div className="w-10 h-10 border-2 border-black flex flex-wrap content-start">
                     {/* Random dots to sim QR */}
                     <div className="w-2 h-2 bg-black m-0.5"></div>
                     <div className="w-2 h-2 bg-black m-0.5"></div>
                     <div className="w-4 h-2 bg-black m-0.5"></div>
                     <div className="w-2 h-2 bg-black m-0.5"></div>
                     <div className="w-2 h-4 bg-black m-0.5"></div>
                     <div className="w-2 h-2 bg-black m-0.5"></div>
                </div>
            </div>
        </div>
      </div>

    </div>
  );
};

export default ShareCard;